sudo: required
services:
  - docker

before_install:
  - docker build -t nahasean/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nahasean/react-test npm test -- --coverage



after_success:
  - docker build -t nahasean/multi-client ./client
  - docker build -t nahasean/multi-nginx ./nginx
  - docker build -t nahasean/multi-server ./server
  - docker build -t nahasean/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nahasean/multi-client
  - docker push nahasean/multi-nginx
  - docker push nahasean/multi-server
  - docker push nahasean/multi-worker